ignorePatterns:
  - "**/lib/*"
  - "**/node_modules/*"
env:
  node: true
  browser: true
  es6: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:react/jsx-runtime"
  - "prettier"
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  tsconfigRootDir: "./"
plugins:
  - "@typescript-eslint"
  - import
  - "prettier"
settings:
  import/resolver:
    typescript: {}
  react:
    version: detect
rules:
  quotes:
    - error
    - single
    - avoidEscape: true
  prettier/prettier:
    - error
    - trailingComma: "all"
      singleQuote: true
      printWidth: 100
      endOfLine: "auto"
      semi: false
  react/prop-types:
    - 0
  react/no-unescaped-entities:
    - 0

